development: &default
  adapter: postgresql
  database: wasabi_dev
  encoding: utf8
  min_messages: warning
  pool: 10
  timeout: 5000
  pool: 30

test:
  <<: *default
  database: wasabi_test

production:
  reaping_frequency: 10
  prepared_statements: true
  statement_limit: 200
